config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, :path => 'users'
  get 'profile', to: 'pages#profile'

  resources :experiences do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :destroy]
  
  resources :grandmothers, except: [:index, :delete]
  delete "grandmothers/:id", to: 'grandmothers#destroy', as: :grandmother_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, required: true
  belongs_to :experience, required: true

  validates :date, :price, presence: true
  validates :price, numericality: true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user, required: true
  belongs_to :grandmother, required: true

  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :title, :description, :price,:start_time, :duration, presence: true
  validates :description, length: { in: 100..500 }
  validates :price, :duration, numericality: true
end

app/models/grandmother.rb
class Grandmother < ApplicationRecord
  belongs_to :user, required: true

  has_many :experiences, dependent: :destroy
  has_one_attached :photo

  validates :name, :age, :nationality, presence: true
  validates :age, numericality: { only_integer: true }
  validates :description, length: { in: 100..500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :grandmothers, dependent: :destroy
  has_one_attached :photo

  validates :name, :age, :location, :email, :password, presence: true
  validates :email, uniqueness: true #format: { with: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/g, message: 'Must enter valid email.' }
  #validates :password, presence: true, if: 'id.nil?' 
  # validates :password, length: { minimum: 8 }, unless: "password.nil?"
  validates :age, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :location, :nationality, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :location, :nationality, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]
  before_action :set_experience, only: [:new, :create]

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.date = booking_params[:date].to_time
    @booking.user = current_user
    @booking.experience = @experience

    @booking.save
  end

  def destroy
    @booking.destroy
    redirect_to profile_path, notice: 'Your booking was cancelled!'
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :price)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @experiences = Experience.where.not(user: current_user)
    else
      @experiences = Experience.all
    end
  end

  def show
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user

    if @experience.save
      redirect_to experience_path(@experience), notice: 'Experience created succesfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @experience.update(experience_params)
      redirect_to experience_path(@experience), notice: 'Experience updated!'
    else
      render :new
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path
  end

  private

  def experience_params
    params.require(:experience).permit(:title, :description, :price,:start_time, :duration, :grandmother_id, :photo)
  end

  def set_experience
    @experience = Experience.find(params[:id])
  end
end

app/controllers/grandmothers_controller.rb
class GrandmothersController < ApplicationController
  before_action :set_grandmother, except: %i[new create]

  def new
    @grandmother = Grandmother.new
  end

  def create
    @grandmother = Grandmother.new(grandmother_params)
    @grandmother.user = current_user

    if @grandmother.save
      redirect_to profile_path, notice: '<strong>Grandmother was created!</strong>'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @grandmother.update(grandmother_params)

    redirect_to profile_path(@grandmother.user), notice: '<strong>Grandma information was updated successfully!</strong>'
  end

  def destroy
    @grandmother.destroy

    redirect_to profile_path, notice: '<strong>Grandmother was deleted!</strong>'
  end

  private

  def set_grandmother
    @grandmother = Grandmother.find(params[:id])
  end

  def grandmother_params
    params.require(:grandmother).permit(:name, :age, :nationality, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @user = current_user
    @bookings = Booking.where(user_id: @user)
    @grandmothers = Grandmother.where(user_id: @user) # I need to fix this so I can have an array of grandmothers belonging to the user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [experience, booking] do |f| %>
  <div class="align-items-center">
    <div>
      <p>Experience</p>
      <h3><%= experience.title %></h3>
      <p><%= f.hidden_field :experience, value: experience.id %></p>
    </div>
    
    <div>
      <p>Date of the event</p>
      <h3><%= Time.now.strftime("%B %d, %Y") %></h3>
      <%= f.hidden_field :date, value: Time.now %>
    </div>

    <div>
      <p>For the modest amount of</p>
      <h3><%= experience.price %>€</h3>
      <%= f.hidden_field :price, value: experience.price %>
    </div>

    <div>
      <p>Who will attend</p>
      <h3><%= current_user.name %></h3>
      <%= f.hidden_field :user, value: current_user.id %>
    </div>
  </div>
  <div class="d-flex justify-content-around">
    <%= link_to 'Go back', experience_path(@experience), class: 'btn action-btn' %>
    <%= f.button :submit, 'Yes! I want to go!', class: 'btn sign-btn', id: 'book-btn' %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<div id="sign-background">
  <div class="container-sign">

    <div class="sign booking-form" id="booking-form" style="display: show;">
      <%= render 'form', experience: @experience, booking: @booking %>
    </div>
    <div class="sign booking-form booking-confirmation align-items-center" id="confirmation-form" style="display: none;">
      <div><h5 class="mt-5">Rejoyce!!</h5></div>
      <div><p class="mt-3">Your booking for:</p></div>
      <div><h3 class="mt-3"><%= @experience.title %></h3></div>
      <div><p class="mt-3 pb-4">is confirmed!</p></div>
      <div><%= link_to 'Go back', profile_path(@user), class: 'btn action-btn mt-4' %></div>

    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<% if @booking.user == current_user %>
  <h1><%= @booking.experience.title %></h1>
  <h2><%= @booking.date.strftime("%B %d, %Y") %></h2>
  <p>For: <%= @booking.user.name %></p>
  <p><%= @booking.experience.duration %>min -- <%= @booking.price %></p>
  <%= link_to 'Cancel booking', booking_path(@booking),
      method: :delete,
      data: { confirm: 'Are you sure?'} %>
<% else %>
  <h1>You cannot access this page!</h1>
<% end %>

<%= link_to 'Profile', profile_path %>

app/views/experiences/_form.html.erb
<%= simple_form_for(experience) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :start_time %>
  <%= f.input :duration, label: 'Duration: (in min)' %>
  <%= f.association :grandmother, label_method: :name, value_method: :id, include_blank: false, collection: current_user.grandmothers  %>
  <%= f.input :photo, as: :file %>
  <div class="btn-container">
    <%= link_to 'Go back', profile_path(@user), class: 'btn action-btn' %>
    <%= f.submit class: 'btn sign-btn' %>
  </div>
<% end %>

app/views/experiences/_form_create.html.erb
<%= simple_form_for @experience do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :duration %>
<%= f.association :grandmother, collection: Grandmother.where(id: current_user.id) %>
<%= f.submit %>
<%= link_to 'Back to list', experiences_path %>
<% end %>

app/views/experiences/edit.html.erb
<h1>Edit experience:</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Back to experience', experience_path(@experience) %>

app/views/experiences/index.html.erb
<div class="exp-page-container">
  <h1>Find an experience near you</h1>
  <div class="row">

      <% @experiences.each do |experience| %>

          <div class="col-sm-12 col-md-6 col-lg-4">
            <div class="exp-container">



               <div class="exp-card-head" style="background-image:url( <%= image_path experience.grandmother.picture %> )">

                <h5><%= link_to experience.title, experience_path(experience) %></h5>
                <p>With <%= experience.grandmother.name %></p>
                </div>


              <div class="card-footer2">
                <div class="price-and-book">
                  <p><%= experience.price %>€</p>
                  <%= link_to 'Book Now', new_experience_booking_path(experience) %>
                </div>
              </div>

            </div>
          </div>

      <% end %>

  </div>
</div>


<!-- removed the delete option in these cards, and will be moved to /profile -->
<!-- <p><%#= link_to 'Delete experience', experience_path(experience),
                      method: :delete,
                      data: { confirm: "Delete #{experience.title}?"} %></p> -->

app/views/experiences/new.html.erb
<div id="experience-background">
  <div class="container-sign">
    <div class="sign">
      <h2>Create an experience</h2>
      <%= render 'form', experience: @experience %>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<div class="exp-page-container">
  <h1><%= @experience.title %></h1>
  <div class="row" >
    <div class="col-sm-12 col-md-4 col-lg-3">
      <div class="grandma-details">
       <!--  <div> -->
<!--         <div class="grandma-dt"> -->
        <% if @experience.grandmother.photo.attached? %>
          <%= cl_image_tag @experience.photo.key, :class => "avatar-medium" %>
        <% else %>
          <%= cl_image_tag "https://images.unsplash.com/photo-1447005497901-b3e9ee359928?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80", :class => "avatar-medium" %>
        <% end %>
          <br>
          <p>Assigned granny</p>
          <h4><%= @experience.grandmother.name %></h4>
<!--         </div> -->

          <div class="text">
            <p><%= @experience.grandmother.description %></p>
         <!--  </div> -->
        </div>
      </div>

      <div class="center-btns">
        <%= link_to 'Go back', profile_path, class: 'btn action-btn' %>
        <%= link_to 'Book Now!', new_experience_booking_path(@experience), class: 'btn sign-btn' %>
      </div>
    </div>

    <div class="col-sm-12 col-md-6 col-lg-8">
      <div class="experience-details">
        <h3>When: <%= @experience.start_time.strftime("%B %d, %Y - %Hh%M") %></h3>
          <div class="details-text">
            <p><%= @experience.description %></p>
          </div>
        <h6>Duration time: <%= @experience.duration %>min</h6>
        <h6><%= @experience.price %>€ </h6>
      </div>
    </div>
  </div>
</div>


<!--     <%#= link_to 'Edit experience', edit_experience_path(@experience) %> -->
<!-- line above might not be useful anymore, since the user -->
<!-- is only seeing the experiences created by others -->
  </div>
</div>

app/views/grandmothers/edit.html.erb
<h1>Grandmothers Edit</h1>

<%= simple_form_for @grandmother do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :nationality %>
  <%= f.input :description, as: :text %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Update grandma!' %>

<% end %>

app/views/grandmothers/new.html.erb
<div id="grandma-background">
  <div class="container-sign">
    <div class="sign">
      <h2>Add a grandmother</h2>

        <%= simple_form_for @grandmother do |f| %>
          <%= f.input :name %>
          <%= f.input :age %>
          <%= f.input :nationality %>
          <%= f.input :description, as: :text %>
          <%= f.input :photo, as: :file %>
          <div class="btn-container">
            <%= link_to 'Go back', profile_path(@user), class: 'btn action-btn' %>
            <%= f.submit 'Create grandma!', class: 'btn sign-btn' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/grandmothers/show.html.erb
<h1>Show Grandma page</h1>
<% if notice.present? %>
  <%= notice.html_safe %>
<% end %>

<%= link_to "edit", edit_grandmother_path(@grandmother) %>



<% if @grandmother.photo.attached? %>
  <%= cl_image_tag @grandmother.photo.key %>
<% else %>
  <%= cl_image_tag "https://images.unsplash.com/photo-1447005497901-b3e9ee359928?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80", :class => "avatar-medium" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrandmaPalooza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', debug: true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

  </head>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' unless current_page?(root_path) %>
    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container-landing">
  <div class="banner">
  <%= render 'shared/home_navbar' %>
    <div class="banner-text text-white">
      <h6 id="bannerh6" style="display: none;">Do you ever come home wishing for some comfort food and wise advice?</h6>
      <p class="mb-0" id="bannerp" style="display: none;">Grandmothers from around the world welcome you into their homes.</p>
      <div id="home-sign" style="display: none;">
        <%= link_to 'Join the community!', new_user_registration_path, class: 'btn sign-btn ml-5 mt-0' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
  <% if notice.present? %>
    <span class="notice-box mt-4" role="alert">
      <%= notice.html_safe %>
    </span>
  <% end %>
<h5 class="greeting">Welcome, <%= @user.name.split(" ").first %>!</h5> <%# to clean %>

<div class="container-profile">
  <div class="row">

    <div class="col-sm-12 col-md-12 col-lg-3">
      <div class="profile-card">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
        <% else %>
          <%= cl_image_tag "https://images.unsplash.com/photo-1447005497901-b3e9ee359928?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80", class: "avatar-large" %>
        <% end %>
        <div class="profile-info">
          <h4><%= @user.name%></h4>
          <small><p><%= @user.nationality %></p></small>
          <small><h5><%= @user.location %></h5></small>
        </div>
        <%= link_to 'Edit',  edit_user_registration_path, class: 'btn action-btn' %>
        <%= link_to 'Log out',  destroy_user_session_path, method: :delete, class: 'btn action-btn' %>
        </div>
      </div>
    <div class="col-sm-12 col-md-12 col-lg-9">
    <div class="dashboard">
      <div id="nav" class="tabs">
          <a href="#manage" class="tab active">Manage Experiences</a>
          <a href="#booked" class="tab">My Booked Experiences</a>
          <a href="#grands" class="tab">Grandmothers</a>
      </div>

      <div class="dashboard-inner">
        <div id="manage" class="toggle" style="display:show">
          <% if @user.experiences.present? %>
            <% @user.experiences.each do |experience| %>
              <div class="section-dash">
                <h6><%= experience.title %></h6>
                <p class="ml-2"><%= experience.description %></p>
                <p>
                <small><span>Host: </span></small><%= experience.grandmother.name %>
                <small><span class="pl-5">Duration: </span></small>
                    <% if experience.duration < 60 %>
                      <%= distance_of_time_in_words(experience.duration * 60) %>
                    <% else %>
                      <%= Time.at(experience.duration * 60).utc.strftime("%H:%M") %> hours
                    <% end %>
                  <small><span class="pl-5">Starts in: </span></small>
                    <%= distance_of_time_in_words(Time.now, experience.start_time) %>
                  <small><span class="pl-5">Price: €</span></small><%= experience.price %>
                </p>
                  <%= link_to 'Edit', edit_experience_path(experience.id), class: 'btn action-btn' %>
                  <%= link_to 'Delete', experience_path(experience.id), method: :delete, class: 'btn action-btn' %>
              </div>
            <% end %>
            <%= link_to 'Create experience', new_experience_path, class: 'btn sign-btn' %>
          <% else %>
            <h6>No experiences.. Yet! </h6>
            <%= link_to 'Create experience', new_experience_path, class: 'btn sign-btn' %>
          <% end %>
        </div>

          <div id="booked" class="toggle" style="display:none">
              <% if @bookings.present? %>
                <% @bookings.each do |booking| %>
                  <div class="section-dash">
                    <h6><%= booking.experience.title %></h6>
                    <p class="ml-2"><%= booking.experience.description %></p>
                    <p>
                    <small><span>Host: </span></small><%= booking.experience.grandmother.name %>
                    <small><span class="pl-5">Duration: </span></small>
                    <% if booking.experience.duration < 60 %>
                      <%= distance_of_time_in_words(booking.experience.duration * 60) %>
                    <% else %>
                      <%= Time.at(booking.experience.duration * 60).utc.strftime("%H:%M") %> hours
                    <% end %>
                    <small><span class="pl-5">Starts in: </span></small>
                    <%= distance_of_time_in_words(Time.now, booking.experience.start_time) %>
                  <small><span class="pl-5">Price: €</span></small><%= booking.experience.price %>
                </p>
                  <%= link_to 'Event page', booking_path(booking.id), class: 'btn action-btn' %>
                  <%= link_to 'Cancel booking', booking_path(booking.id), method: :delete, class: 'btn action-btn' %>
              </div>
              <% end %>
                  <div class="d-flex justify-content-center align-center">
                  <%= link_to 'Explore all experiences', experiences_path, class: 'btn sign-btn' %>
                    <div class="searchbar bg-white mt-3">
                      <input class="search_input bg-white" type="text" name="" placeholder="Search by experiences, country, or type of food..">
                      <a href="#" class="search_icon text-dark"><i class="fas fa-search"></i></a>
                    </div>
                  </div>
            <% else %>
                <h6>No bookings.. Yet!</h6>
            <% end %>
        </div>

        <div id="grands" class="toggle" style="display:none">
          <% if @grandmothers.present? %>
            <% @grandmothers.each do |grandmother| %>
                  <div class="section-dash">
                    <h6><%= grandmother.name %></h6>
                    <p><small>
                      <%= grandmother.nationality %>,
                      <%= grandmother.age %> years young
                    </small></p>
                    <p class="ml-2"><%= grandmother.description %></p>
                    <%= link_to 'Edit', edit_grandmother_path(grandmother.id), class: 'btn action-btn' %>
                    <%= link_to 'Delete', grandmother_destroy_path(grandmother), method: :delete, class: 'btn action-btn' %>
                  </div>
            <% end %>
            <%= link_to 'Add grandmother', new_grandmother_path, class: 'btn sign-btn' %>
          <% else %>
            <h6>Add your granny!</h6>
            <%= link_to 'Add grandmother', new_grandmother_path, class: 'btn sign-btn' %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p> Grandma Palooza &#169; was created with <i class="far fa-heart"></i> at Le Wagon | <%= DateTime.now.year %></p>
</div>

app/views/shared/_home_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="transparent-black">
      <%= link_to root_path, class: "navbar-brand" do %>
        <h1 class="text-white nav-title">Grandma Palooza</h1>
      <% end %>
      <%# Search bar %>
      <div class="container center-item">
      <div class="d-flex justify-content-center">
        <div class="searchbar">
          <input class="search_input" type="text" name="" placeholder="Search by experiences, country, or type of food..">
          <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
        </div>
      </div>
    </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Experiences", experiences_path, class: "nav-link text-white mx-5 override-font" %>
          </li>

          <li class="nav-item">
            <%= link_to "Dashboard", profile_path, class: "nav-link mx-5 override-font text-white" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag "https://images.unsplash.com/photo-1447005497901-b3e9ee359928?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", profile_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
            <% else %>
                <%= link_to 'Log in', new_user_session_path, id: 'btn-login' %>
            <% end %>
        </ul>
      </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand" do %>
        <h1 class="text-dark nav-title" id="shadow-light">Grandma Palooza</h1>
      <% end %>
      <%# Search bar %>
      <div class="container ml-3">
      <div class="d-flex justify-content-center">
        <div class="searchbar bg-white">
          <input class="search_input bg-white" type="text" name="" placeholder="Search by experiences, country, or type of food..">
          <a href="#" class="search_icon text-dark"><i class="fas fa-search"></i></a>
        </div>
      </div>
    </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Experiences", experiences_path, class: "nav-link mx-5 override-font text-dark" %>
          </li>

          <li class="nav-item">
            <%= link_to "Dashboard", profile_path, class: "nav-link mx-5 override-font text-dark" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag "https://images.unsplash.com/photo-1447005497901-b3e9ee359928?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", profile_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
            <% else %>
                <%= link_to 'Log in', new_user_session_path, id: 'btn-login' %>
            <% end %>
        </ul>
      </div>
    </div>